#!/bin/sh
. /home/vpsscript.conf
website=$(cat /tmp/vpsscript-tensitephuchoi)
dataname=$(cat /tmp/vpsscript-tendatabasephuchoi)
randomcode=`date |md5sum |cut -c '1-18'`   
echo "========================================================================="
	echo "Tim thay file backup vpsscript-DATABASE.tar.gz"
	echo "-------------------------------------------------------------------------"
	echo "Chuan bi phuc hoi .... "
	sleep 2
	gunzip < /home/$website/public_html/vpsscript-DATABASE.tar.gz | mysql -u root -p$mariadbpass $dataname
	date -r /var/lib/mysql/$dataname +%H%M%S> /tmp/vpsscript2
	check1=`cat /tmp/vpsscript1`
	check2=`cat /tmp/vpsscript2`
		if [ "$check1" == "$check2" ]; then
		rm -rf /tmp/*vpsscript*
		sleep 8
		clear
		echo "========================================================================="
		echo "Phuc hoi database $dataname that bai "
		echo "-------------------------------------------------------------------------"
		echo "Vui long kiem tra file backup va thu lai !"
		/etc/vpsscript/menu/vpsscript-them-xoa-database
		else	
		rm -rf /tmp/*vpsscript*
		mv /home/$website/public_html/vpsscript-DATABASE.tar.gz /home/$website/public_html/vpsscript-DATABASE.tar.gz.$randomcode
		clear
		echo "========================================================================="
		echo "Phuc hoi database $dataname thanh cong !"
		echo "-------------------------------------------------------------------------"
		echo "File backup duoc doi ten thanh vpsscript-DATABASE.tar.gz.$randomcode"
		/etc/vpsscript/menu/vpsscript-them-xoa-database
		exit
		fi
