#!/bin/sh
. /home/vpsscript.conf
if [ ! -f /etc/vpsscript/net2ftpsite.info ]; then
clear
echo "========================================================================="
echo "Ban chua cai dat domain Net2FTP cho Server !"
/etc/vpsscript/menu/vpsscript-net2ftp-menu
exit
fi
echo "Please wait..."; sleep 1
net2ftpsite=$(cat /etc/vpsscript/net2ftpsite.info)
clear
echo "========================================================================="
echo "Domain Net2FTP: $net2ftpsite"
/etc/vpsscript/menu/vpsscript-net2ftp-menu
