#!/bin/sh
. /home/vpsscript.conf
website=$(cat /tmp/vpsscript-tensitephuchoi)
dataname=$(cat /tmp/vpsscript-tendatabasephuchoi)
randomcode=`date |md5sum |cut -c '1-18'`
echo "========================================================================="
	echo "Tim thay file backup vpsscript-DATABASE.zip"
	echo "-------------------------------------------------------------------------"
	echo "Chuan bi phuc hoi .... "
	sleep 2
	rm -rf /tmp/vpsscript-sql
	mkdir -p /tmp/vpsscript-sql
	unzip /home/$website/public_html/vpsscript-DATABASE.zip -d /tmp/vpsscript-sql
	ls /tmp/vpsscript-sql > /tmp/vpsscript-datasql-name
	tenbackup=$(cat /tmp/vpsscript-datasql-name)
	mysql -u root -p$mariadbpass $dataname < /tmp/vpsscript-sql/$tenbackup > /tmp/abc
	date -r /var/lib/mysql/$dataname +%H%M%S> /tmp/vpsscript2
	rm -rf /tmp/vpsscript-sql/$tenbackup
	check1=`cat /tmp/vpsscript1`
	check2=`cat /tmp/vpsscript2`
		if [ "$check1" == "$check2" ]; then
		rm -rf /tmp/*vpsscript*
		sleep 8
		clear
		echo "========================================================================="
		echo "Phuc hoi database $dataname that bai "
		echo "-------------------------------------------------------------------------"
		echo "Vui long kiem tra file backup va thu lai !"
		/etc/vpsscript/menu/vpsscript-them-xoa-database
		else	
		rm -rf /tmp/*vpsscript*
		mv /home/$website/public_html/vpsscript-DATABASE.zip /home/$website/public_html/vpsscript-DATABASE.zip.$randomcode
		clear
		echo "========================================================================="
		echo "Phuc hoi database $dataname thanh cong !"
		echo "-------------------------------------------------------------------------"
		echo "File backup duoc doi ten thanh vpsscript-DATABASE.zip.$randomcode"
		/etc/vpsscript/menu/vpsscript-them-xoa-database
		exit
		fi
