#!/bin/bash
prompt="Lua chon cua ban (0-Thoat):"
options=( "Thay Password Root" "Fix Loi Chmod, Chown" "Find Top Largest Files & Folders" "Service Running & Ram Use" "Kiem Tra IP/Nameserver Website" \
"File Size Converter " "Kiem Tra Thong Tin Server" "Cai Dat Server Timezone" "Install / Remove Imagick" "Install / Remove Ioncube" "Cai Dat Htop" \
"Backup Config File & Vhost" "Thay Doi Port SSH Number" "Config SSH Timeout" "Block Exploits, SQL Injections" "Deny Run Script In Upload Folder" \
"Dat Mat Khau Bao Ve Folder" "BAT/TAT Email Thong Bao Login" "BAT/TAT Auto Run vpsscript" "Canh Bao Full Disc Tren Menu" "Restart Service" "TocDo.net" \
"Varnish Cache" "Update All Website Wordpress" "Install Composer" "Go Bo (Remove) vpsscript" )
printf "=========================================================================\n"
printf "                OKVIP-VPSSCRIPT - Quan Ly VPS/ Server by EchBay.com \n"
printf "=========================================================================\n"
printf "                           Tien Ich - Addons\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


	1) /etc/vpsscript/menu/vpsscript-doi-pass-root-vps;;
	2) /etc/vpsscript/menu/vpsscript-sua-loi-chown;;
	3) /etc/vpsscript/menu/tienich/vpsscript-xem-danh-sach-max-dung-luong-file-menu;;
	4) /etc/vpsscript/menu/tienich/vpsscript-dich-vu-dang-chay-va-ram-dung;;
	5) /etc/vpsscript/menu/tienich/vpsscript-tim-ip-nameserver-website;;
	6) /etc/vpsscript/menu/vpsscript-chuyen-doi-don-vi-file-size-convert;;
	7) /etc/vpsscript/menu/tienich/vpsscript-view-thong-tin-ip-vps;;
	8) clear && /etc/vpsscript/menu/vpsscript-thay-doi-thong-tin-thoi-gian;; 
	9) /etc/vpsscript/menu/tienich/vpsscript-before-imagick;;
	10) /etc/vpsscript/menu/tienich/vpsscript-before-ioncube;;
	11) /etc/vpsscript/menu/tienich/vpsscript-cai-dat-htop;;
	12) /etc/vpsscript/menu/vpsscript-sao-luu-sys;;
	13) /etc/vpsscript/menu/thay-doi-port-ssh;;
	14) /etc/vpsscript/menu/vpsscript-bat-tat-ssh-time-out;;
	15) /etc/vpsscript/menu/vpsscript-block-exploits-sql-injections-menu;;
	16) /etc/vpsscript/menu/vpsscript-chan-run-script-trong-folder-upload-menu;;
	17) /etc/vpsscript/menu/vpsscript-dat-mat-khau-bao-ve-folder-website;;
	18) /etc/vpsscript/menu/bat-tat-email-thong-bao-dang-nhap-server;;
	19) /etc/vpsscript/menu/vpsscript-bat-tat-tu-dong-chay-vpsscript;;
	20) /etc/vpsscript/menu/vpsscript-config-canh-bao-dung-luong-disc-trong-free-it;;
	21) clear && /etc/vpsscript/menu/tienich/vpsscript-restart-service;;
	22) clear && /etc/vpsscript/menu/tienich/toc-do-dot-net;;
	23) clear && /etc/vpsscript/menu/varnish/install-varnish;;
	24) clear && /etc/vpsscript/menu/tienich/update-wordpress-for-all-site;;
	25) clear && /etc/vpsscript/menu/tienich/install-composer;;
	26) /etc/vpsscript/menu/go-bo-scripts;;
#	23) clear && vpsscript;;
	0) clear && vpsscript;;


            *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done
