#!/bin/bash
. /home/vpsscript.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpsscript/menu/nang-cap-nginx
else
echo "-------------------------------------------------------------------------"
service nginx start
if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpsscript/menu/nang-cap-nginx
else
clear
echo "========================================================================="
echo "Rat tiec, Nginx dang stopped. Hay bat len truoc khi dung chuc nang nay!"
#echo "Sorry, Nginx is stopped. Please start it before use this function !"
/etc/vpsscript/menu/vpsscript-update-upgrade-service-menu
fi
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "`systemctl is-active nginx.service`" == "active" ]; then
/etc/vpsscript/menu/nang-cap-nginx
else
systemctl start nginx.service
if [ "`systemctl is-active nginx.service`" == "active" ]; then
/etc/vpsscript/menu/nang-cap-nginx
else
clear
echo "========================================================================="
echo "Rat tiec, Nginx dang stopped. Hay bat len truoc khi dung chuc nang nay!"
#echo "Sorry, Nginx is stopped. Please start it before use this function !"
/etc/vpsscript/menu/vpsscript-update-upgrade-service-menu
fi
fi
fi
