#!/bin/sh
. /home/vpsscript.conf
if [ ! -f /etc/php.ini ]; then
clear
echo "========================================================================="
echo "vpsscript khong tim thay php.ini tren server"
/etc/vpsscript/menu/vpsscript-config-php.ini-menu
exit
fi

if [ "$(cat /etc/php.ini | grep display_errors | awk '{print $3}')" == "" ]; then
clear
echo "========================================================================="
echo "vpsscript khong the thuc hien chuc nang nay"
/etc/vpsscript/menu/vpsscript-config-php.ini-menu
exit
fi

if [ "$(cat /etc/php.ini | grep display_errors | awk '{print $3}')" == "Off" ]; then
/etc/vpsscript/menu/vpsscript-dang-tat-display_errors
fi
if [ "$(cat /etc/php.ini | grep display_errors | awk '{print $3}')" == "On" ]; then
/etc/vpsscript/menu/vpsscript-dang-bat-display_errors
fi
}
