#!/bin/bash
. /home/vpsscript.conf

if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
clear
echo "========================================================================= "
echo "FTP Server chua duoc cai dat "
echo "-------------------------------------------------------------------------"
echo "Ban phai cai dat chuc nang Setup FTP server truoc"
/etc/vpsscript/menu/vpsscript-ftpserver-menu
exit
fi

#
if [ "$1" = "" ]; then
echo "========================================================================="
echo "Su dung chuc nang nay de tao FTP user cho  website"
echo "-------------------------------------------------------------------------"
echo -n "Nhap website ban muon them FTP user [ENTER]: " 
read website
else
website=$1
fi

if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap lai!"
/etc/vpsscript/menu/vpsscript-ftpserver-menu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co le khong phai la domain !"
echo "-------------------------------------------------------------------------"
echo "Ban vui long nhap lai  !"
/etc/vpsscript/menu/vpsscript-ftpserver-menu
exit
fi

if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Website $website khong ton tai tren he thong!"
echo "-------------------------------------------------------------------------"
echo "Ban hay nhap lai !"
/etc/vpsscript/menu/vpsscript-ftpserver-menu
exit
fi

if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi

if [ ! "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "Ban da tao tai khoan FTP cho $website" 
echo "-------------------------------------------------------------------------"
echo "Thong tin tai khoan FTP:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $(grep "/home/$website/" /etc/vpsscript/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/vpsscript/FTP-Account.info | awk 'NR==1 {print $10}')"
/etc/vpsscript/menu/vpsscript-ftpserver-menu
fi


echo "-------------------------------------------------------------------------"
echo "Tim thay $website tren he thong"
echo "-------------------------------------------------------------------------"
echo "$website chua tao tai khoan FTP"
echo "-------------------------------------------------------------------------"
echo "vpsscript se tao tai khoan FTP cho $website ngay bay gio"
echo "-------------------------------------------------------------------------"
echo "Please wait..."; sleep 6


#echo "$website" > /tmp/vpsscriptftp.txt
#sed -i 's/\.//g' /tmp/vpsscriptftp.txt
#sed -i 's/\-//g' /tmp/vpsscriptftp.txt
#username=`cat /tmp/vpsscriptftp.txt | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | cut -c1-30`
username="ftp@"$website
password=`date |md5sum |cut -c '1-16'`
#useradd -m -d /home/$website -g nginx -p $password $username
#usermod -aG nginx $username
#chmod g+rxw /home/$website
( echo ${password} ; echo ${password} ) | pure-pw useradd $username -u nginx -g nginx -d /home/$website -m 
pure-pw mkdb
rm -rf /tmp/ftpvpsscript.temp;
pure-pw mkdb

if [ ! -f /etc/vpsscript/FTP-Account.info ]; then
echo "=========================================================================" > /etc/vpsscript/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/vpsscript/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpsscript/FTP-Account.info
echo "If you delete this file, vpsscript will not run !" >> /etc/vpsscript/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpsscript/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/vpsscript/FTP-Account.info
echo "=========================================================================" >> /etc/vpsscript/FTP-Account.info
echo "" >> /etc/vpsscript/FTP-Account.info
fi

################
echo "FTP Account for $website | Username: $username | Password: $password | dd /home/$website/ " >> /etc/vpsscript/FTP-Account.info
clear
echo "=========================================================================" 
echo "Tao tai khoan FTP cho $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Thong tin login:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $password"

#
/etc/vpsscript/menu/vpsscript-ftpserver-menu
