#!/bin/sh
. /home/vpsscript.conf
rm -rf /tmp/*hostingaz*
mkdir -p /tmp/saoluuwebsitethanhconghostingaz
mkdir -p /tmp/saoluuwebsitethatbaihostingaz
ls /etc/nginx/conf.d > /tmp/vpsscript-websitelist
sed -i 's/\.conf//g' /tmp/vpsscript-websitelist 
 cat > "/tmp/vpsscript-replace" <<END
sed -i '/$mainsite/d' /tmp/vpsscript-websitelist
END
chmod +x /tmp/vpsscript-replace
/tmp/vpsscript-replace
rm -rf /tmp/vpsscript-replace
rm -rf /tmp/checksite-list
sowebsitetrenserver=$(cat /tmp/vpsscript-websitelist | wc -l)
listwebsite=$(cat /tmp/vpsscript-websitelist)
rm -rf /tmp/checksite-list
for checksite in $listwebsite 
do
if [ -f /home/$checksite/public_html/index.php ]; then
echo "$checksite" >> /tmp/checksite-list
fi
 done

if [ ! -f /tmp/checksite-list ]; then
rm -rf /tmp/*vpsscript*
rm -rf /tmp/*hostingaz*
clear
echo "========================================================================="
echo "Khong tim thay website co du lieu tren server"
/etc/vpsscript/menu/vpsscript-sao-luu
fi
prompt="Nhap lua chon cua ban :"
options=("BAT/TAT Tu Dong Backup Website" "List Website BAT Tu Dong Backup")
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1 ) /etc/vpsscript/menu/vpsscript-befor-chon-tat-bat-tu-dong-sao-luu-code;;
    2 ) /etc/vpsscript/menu/vpsscript-danh-sach-website-tu-dong-sao-luu-code;;
    $(( ${#options[@]}+1 )) ) echo "";  clear && /etc/vpsscript/menu/vpsscript-sao-luu;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;

    esac
done
