#!/bin/sh
. /home/vpsscript.conf
rm -rf /tmp/vpsscript*
echo "-------------------------------------------------------------------------"
echo "Please wait. vpsscript dang kiem tra ..."; sleep 1
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
		echo "Memcached: Running | Ram Usage: `grep CACHESIZE= /etc/sysconfig/memcached | grep -o '[0-9]*'` MB"  > /tmp/vpsscript-memcached-info.txt
	else
		echo "Memcached: Stopped"  > /tmp/vpsscript-memcached-info.txt
	fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "`systemctl is-active memcached.service`" == "active" ]; then
		echo "Memcached: Running | Ram Usage: `grep CACHESIZE= /etc/sysconfig/memcached | grep -o '[0-9]*'` MB"  > /tmp/vpsscript-memcached-info.txt
	else
		echo "Memcached: Stopped"  > /tmp/vpsscript-memcached-info.txt
	fi
fi

if [ ! -f /etc/vpsscript/uploadsite ]; then 
echo "File Manager: Not Install " > /tmp/vpsscript-filemanager-info.txt
else
uploadsite=$(cat /etc/vpsscript/uploadsite)
echo "File Manager: Installed | Domain: $uploadsite" > /tmp/vpsscript-filemanager-info.txt
fi

if [ ! -f /etc/vpsscript/net2ftpsite.info ]; then 
echo "Net2FTP: Not Install " > /tmp/vpsscript-net2ftp-info.txt
else
net2ftpsite=$(cat /etc/vpsscript/net2ftpsite.info)
echo "Net2FTP: Installed | Domain: $net2ftpsite" > /tmp/vpsscript-net2ftp-info.txt
fi

if [ ! -f /etc/vpsscript/netdatasite.info ]; then 
echo "NetData: Not Install " > /tmp/vpsscript-netdata-info.txt
else
netdatasite=$(cat /etc/vpsscript/netdatasite.info)
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service netdata status | awk 'NR==1 {print $5}')" == "running..." ]; then
echo "NetData: Installed & Enable | Domain: $netdatasite" > /tmp/vpsscript-netdata-info.txt
	else
echo "NetData: Installed But Disable | Domain: $netdatasite" > /tmp/vpsscript-netdata-info.txt
	fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "`systemctl is-active netdata.service`" == "active" ]; then
echo "NetData: Installed & Enable | Domain: $netdatasite" > /tmp/vpsscript-netdata-info.txt
	else
echo "NetData: Installed But Disable | Domain: $netdatasite" > /tmp/vpsscript-netdata-info.txt
	fi
fi
fi


if [ ! -f "/etc/csf/csf.conf" ]; then
echo "CSF Firewall: Not install" > /tmp/vpsscript-csf-firewall-info.txt
else
csf -v > /tmp/vpsscriptcheckcscfstatus
if [ "$(grep disabled /tmp/vpsscriptcheckcscfstatus)" = "" ]; then
echo "CSF Firewall: installed | Version: $(csf -v | awk 'NR==1 {print $2}' | sed 's/v//') " > /tmp/vpsscript-csf-firewall-info.txt
else
echo "CSF Firewall: Installed but Disable" > /tmp/vpsscript-csf-firewall-info.txt
fi
fi


# /etc/vpsscript/menu/vpsscript-befor-vps-info-redis


if [ -f /var/lib/mysql/vpsscriptCheckDB/db.opt ]; then
rm -rf /var/lib/mysql/vpsscriptCheckDB
fi
 cat > "/tmp/config.temp" <<END
CREATE DATABASE vpsscriptCheckDB COLLATE utf8_general_ci;
END
mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp

if [ ! -f /var/lib/mysql/vpsscriptCheckDB/db.opt ]; then
clear
echo "========================================================================"
echo "MySQL service is not running"
echo "------------------------------------------------------------------------"
echo "vpsscript trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5
rm -rf /var/lib/mysql/ib_logfile0
rm -rf /var/lib/mysql/ib_logfile1
cat > "/tmp/startmysql" <<END
systemctl start mariadb.service
service mysql start
END
chmod +x /tmp/startmysql
/tmp/startmysql
rm -rf /tmp/startmysql
clear
echo "========================================================================"
echo "Check MySQL service once again !"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5
cat > "/tmp/config.temp" <<END
CREATE DATABASE vpsscriptCheckDB COLLATE utf8_general_ci;
END
mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp
	if [ ! -f /var/lib/mysql/vpsscriptCheckDB/db.opt ]; then
		clear
echo "========================================================================"
echo "vpsscript can not start MySQL Service"
sleep 4 ;
echo "MySQL Status: Stopped" > /tmp/vpsscript-mysql-info.txt
	else
	rm -rf /var/lib/mysql/vpsscriptCheckDB
echo "MySQL Status: Running" > /tmp/vpsscript-mysql-info.txt
	fi
else
rm -rf /var/lib/mysql/vpsscriptCheckDB
echo "MySQL Status: Running" > /tmp/vpsscript-mysql-info.txt
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
echo "Nginx Status: Running" > /tmp/vpsscript-nginx-info.txt
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "vpsscript trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
service nginx start
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
		if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
echo "Nginx Status: Running" > /tmp/vpsscript-nginx-info.txt
		else
		clear
echo "========================================================================"
echo "vpsscript can not start Nginx Service"
sleep 4 ;
echo "Nginx Status: Stopped" > /tmp/vpsscript-nginx-info.txt
		fi
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "`systemctl is-active nginx.service`" == "active" ]; then

echo "Nginx Status: Running" > /tmp/vpsscript-nginx-info.txt
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "vpsscript trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
systemctl start nginx.service
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
	if [ "`systemctl is-active nginx.service`" == "active" ]; then

echo "Nginx Status: Running" > /tmp/vpsscript-nginx-info.txt
		else
		clear
echo "========================================================================"
echo "vpsscript can not start Nginx Service"
sleep 4 ;
echo "Nginx Status: Stopped" > /tmp/vpsscript-nginx-info.txt
		fi
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
	echo "PHP Status: Running" > /tmp/vpsscript-php-info.txt
	echo "PHP version: $(php -i | grep 'PHP Version' | awk 'NR==1 {print $4}') " >> /tmp/vpsscript-php-info.txt
	else
clear
echo "========================================================================"
echo "PHP-FPM service is not running"
echo "------------------------------------------------------------------------"
echo "vpsscript trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
	echo "-------------------------------------------------------------------------"
service php-fpm start
clear
echo "========================================================================"
echo "Check PHP-FPM service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
			if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
	echo "PHP Status: Running" > /tmp/vpsscript-php-info.txt
	echo "PHP version: $(php -i | grep 'PHP Version' | awk 'NR==1 {print $4}') " >> /tmp/vpsscript-php-info.txt
		else
	clear
echo "========================================================================"
echo "vpsscript can not start PHP-FPM Service"
sleep 4 ;
	echo "PHP Status: Stopped" >> /tmp/vpsscript-php-info.txt
		fi
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
	echo "PHP Status: Running" > /tmp/vpsscript-php-info.txt
	echo "PHP version: $(php -i | grep 'PHP Version' | awk 'NR==1 {print $4}') " >> /tmp/vpsscript-php-info.txt
	else
clear
echo "========================================================================"
echo "PHP-FPM service is not running"
echo "------------------------------------------------------------------------"
echo "vpsscript trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
	echo "-------------------------------------------------------------------------"
systemctl start php-fpm.service
clear
echo "========================================================================"
echo "Check PHP-FPM service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
	echo "PHP Status: Running" > /tmp/vpsscript-php-info.txt
	echo "PHP version: $(php -i | grep 'PHP Version' | awk 'NR==1 {print $4}') " >> /tmp/vpsscript-php-info.txt
		else
		clear
echo "========================================================================"
echo "vpsscript can not start PHP-FPM Service"
sleep 4 ;
	echo "PHP Status: Stopped" >> /tmp/vpsscript-php-info.txt
		fi
fi
fi
