#!/bin/sh
. /home/vpsscript.conf
if [ "$(grep HostingAZ.VN /bin/vpsscript)" != "" ]; then
clear
echo "========================================================================= "
echo "You are using Vietnamese Version"
echo "-------------------------------------------------------------------------"
echo "( Ban dang su dung ngon ngu Tieng Viet )"
/etc/vpsscript/menu/vpsscript-thay-doi-ngon-ngu-menu
exit
fi

echo "========================================================================= "
echo "Su dung chuc nang nay de thay doi ngon ngu vpsscript sang tieng Viet"
echo "-------------------------------------------------------------------------"
echo "vpsscript ho tro Tieng Anh & Tieng Viet"
echo "========================================================================= "
read -r -p "Ban muon thay doi ngon ngu vpsscript sang Tieng Viet ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
echo "-------------------------------------------------------------------------"
wget -q --no-check-certificate https://hostingaz.vn/script/vpsscript/motd -O /etc/motd
wget -q --no-check-certificate https://hostingaz.vn/script/vpsscript/vpsscript -O /bin/vpsscript && chmod +x /bin/vpsscript
cd /etc/vpsscript/
rm -rf /etc/vpsscript/menu.zip
wget -q --no-check-certificate https://hostingaz.vn/script/vpsscript/menu.zip

#Check menu.zip files

rm -rf /tmp/menu
unzip -q -o menu.zip -d /tmp
if [ ! -f /tmp/menu/vpsscript-tien-ich ]; then
rm -rf /tmp/menu
clear
echo "========================================================================="
echo "There's an error in changing language process"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpsscript/menu/vpsscript-update-upgrade-service-menu
exit
fi
## Finish check menu.zip
rm -rf /tmp/menu
unzip -q -o menu.zip
rm -rf /etc/vpsscript/menu.zip
cd
wget -q --no-check-certificate https://hostingaz.vn/script/vpsscript/motd -O /etc/motd
download_main_menu () {
wget -q --no-check-certificate https://hostingaz.vn/script/vpsscript/vpsscript -O /bin/vpsscript && chmod +x /bin/vpsscript
}
download_main_menu
checkvpsscript_mainmenu=`cat /bin/vpsscript`
if [ -z "$checkvpsscript_mainmenu" ]; then
download_main_menu
fi
find /etc/vpsscript/menu -type f -exec chmod 755 {} \;
clear 
echo "========================================================================= "
echo "Change Language of vpsscript to Vietnamese Finished"
echo "-------------------------------------------------------------------------"
echo "( Thay doi ngon ngu vpsscript sang tieng Viet thanh cong )"
/etc/vpsscript/menu/vpsscript-thay-doi-ngon-ngu-menu
       ;;
    *)
        echo ""
        ;;
esac
clear
clear
echo "========================================================================="
echo "Cancel Change Language for vpsscript"
echo "-------------------------------------------------------------------------"
echo "Huy bo thay doi ngon ngu cho vpsscript"
/etc/vpsscript/menu/vpsscript-thay-doi-ngon-ngu-menu
