#!/bin/sh
. /home/vpsscript.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpsscript/menu/memcache/vpsscript-tat-memcache
exit
fi
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
/etc/vpsscript/menu/memcache/vpsscript-bat-memcache
clear
exit
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "`systemctl is-active memcached.service`" == "active" ]; then
clear
/etc/vpsscript/menu/memcache/vpsscript-tat-memcache
exit
fi
if [ ! "`systemctl is-active memcached.service`" == "active" ]; then
clear
/etc/vpsscript/menu/memcache/vpsscript-bat-memcache
exit
fi
fi
clear
echo "========================================================================="
echo "Sorry, OKVIP-VPSSCRIPT khong phat hien Memcached tren he thong !"
vpsscript
exit
fi
