#!/bin/sh
. /home/vpsscript.conf
prompt="Lua chon cua ban (0-Thoat):"
options=("Bat Zend Opcache" "Cau Hinh Zend Opcache" "Them Website Vao BlackList" "Xoa Website Khoi Blacklist" "Clear Zend OPcache")
printf "=========================================================================\n"
printf "                vpsscript - Quan Ly VPS/ Server by EchBay.com \n"
printf "=========================================================================\n"
printf "                          Zend OPcache Manage \n"
printf "=========================================================================\n"
printf "                    Zend Opcache Current: Disable\n"
printf "=========================================================================\n"
printf "Zend Opcache Manage Link: http://$serverip:$priport/ocp.php\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
	1 ) /etc/vpsscript/menu/opcache/vpsscript-bat-opcache;;
	2 ) /etc/vpsscript/menu/opcache/vpsscript-opcache-change-size;;
	3) /etc/vpsscript/menu/opcache/vpsscript-them-website-vao-blacklist;;
	4) /etc/vpsscript/menu/opcache/vpsscript-xoa-website-khoi-blacklist;;
	5) /etc/vpsscript/menu/opcache/vpsscript-clear-opcache;;
	#$(( ${#options[@]}+1 )) ) echo "";  clear && /bin/vpsscript;;
	0) echo "";  clear && /bin/vpsscript;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;

    esac
done
