#!/bin/bash

# Kiểm tra quyền root
if [ "$EUID" -ne 0 ]; then
  echo "Vui lòng chạy với quyền root."
  exit 1
fi

APP_NAME=$1
if [ -z "$APP_NAME" ]; then
  echo "Sử dụng: ./reload-app <app_name>"
  exit 1
fi

echo "Reload $APP_NAME..."
systemctl reload $APP_NAME

if [ $? -eq 0 ]; then
  echo "$APP_NAME đã được reload thành công!"
else
  echo "Có lỗi xảy ra khi reload $APP_NAME!"
fi
