#!/bin/bash

#
echo "========================================================================="
echo "Coming soon..."
echo "-------------------------------------------------------------------------"

#
/etc/vpsscript/menu/centos9/option/security-firewall-menu
exit
