#!/bin/bash 

. /home/vpsscript.conf
if [ -f /etc/csf/csf.conf ]; then
echo "Please wait....";sleep 1
csf -e
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-re-start-khoi-dong-lai-csf-lfd
clear
echo "========================================================================= "
echo "CSF Firewall da bat va khoi dong lai thanh cong. ! "
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-csf-firewall-menu
else
echo "========================================================================= "
echo "Chuc nang nay can CSF Firewall de hoat dong"
echo "-------------------------------------------------------------------------"
echo "CSF Firewall chua cai dat tren server "
echo "-------------------------------------------------------------------------"
read -r -p "Ban co muon cai dat CSF Firewall ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-cai-dat-csf-csf
clear
echo "========================================================================= "
echo "Cai dat va config thanh cong CSF Firewall"
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-csf-firewall-menu
;;
esac
clear
echo "========================================================================= "
echo "Ban huy bo cai dat CSF Firewall ! "
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-csf-firewall-menu
exit
fi
