#!/bin/bash 

. /home/vpsscript.conf

if [ -f /etc/csf/csf.conf ]; then
clear
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-csf-firewall-menu
else
echo "========================================================================= "
echo "Chuc nang nay can CSF Firewall de hoat dong"
echo "-------------------------------------------------------------------------"
echo "CSF Firewall chua duoc cai dat tren server! "
echo "-------------------------------------------------------------------------"
read -r -p "Ban co muon cai dat CSF Firewall ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-cai-dat-csf-csf
clear
echo "========================================================================= "
echo "Cai dat va config thanh cong CSF Firewall."
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-csf-firewall-menu
;;
esac
clear
echo "========================================================================= "
echo "Ban huy bo cai dat CSF Firewall ! "
/etc/vpsscript/menu/CSF-Fiwall/vpsscript-csf-firewall-menu
exit
fi
