#!/bin/bash
. /home/vpsscript.conf
if [ ! -f /etc/vpsscript/iptables.bak ]; then
clear
echo "========================================================================="
echo "vpsscript khong tim thay ban backup cua IPtables Firewall !"
/etc/vpsscript/menu/vpsscript-iptables-firewall-manager-menu
exit
fi
echo "--------------------------------------------------------------------------"
echo "Tim thay ban backup cua IPtable Firewall"
echo "--------------------------------------------------------------------------"
echo "File Backup duoc tao vao: $(date -r /etc/vpsscript/iptables.bak +%H:%M/%F)"
echo "--------------------------------------------------------------------------"

read -r -p "Ban muon phuc hoi IPtables Firewall tu file backup nay ? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
echo "--------------------------------------------------------------------------"
echo "Please wait..."
sleep 1
iptables-restore < /etc/vpsscript/iptables.bak
service iptables save

clear
echo "========================================================================="
echo "Phuc hoi IPtables Firewall Rules hoan thanh !"
/etc/vpsscript/menu/vpsscript-iptables-firewall-manager-menu
else
clear
echo "========================================================================="
echo "Ban da huy phuc hoi IPtables Firewall Rules !"
/etc/vpsscript/menu/vpsscript-iptables-firewall-manager-menu
fi
