#!/bin/sh
. /home/vpsscript.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
clear
echo "========================================================================"
service php-fpm restart
/etc/vpsscript/menu/tienich/vpsscript-restart-service
	else
clear
echo "========================================================================"
echo "php-fpm service is not running"
echo "------------------------------------------------------------------------"
echo "vpsscript trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
		echo "-------------------------------------------------------------------------"
service php-fpm start
clear
echo "========================================================================"
echo "Check php-fpm service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
		if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
clear
echo "========================================================================"
service php-fpm restart
/etc/vpsscript/menu/tienich/vpsscript-restart-service
		else
		clear
echo "========================================================================"
echo "vpsscript can not start php-fpm Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, vpsscript khong the khoi dong lai duoc php-fpm service !"
	#echo "Sorry, vpsscript can not restart php-fpm service !"
	/etc/vpsscript/menu/tienich/vpsscript-restart-service
		fi
fi
fi
#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
clear
echo "========================================================================"
service php-fpm stop
service php-fpm start
/etc/vpsscript/menu/tienich/vpsscript-restart-service
	else
clear
echo "========================================================================"
echo "php-fpm service is not running"
echo "------------------------------------------------------------------------"
echo "vpsscript trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
		echo "-------------------------------------------------------------------------"
systemctl restart php-fpm.service
clear
echo "========================================================================"
echo "Check php-fpm service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
	if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
clear
echo "========================================================================"
service php-fpm stop
service php-fpm start
/etc/vpsscript/menu/tienich/vpsscript-restart-service
		else
				clear
echo "========================================================================"
echo "vpsscript can not start php-fpm Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, vpsscript khong the khoi dong lai duoc php-fpm!"
	#echo "Sorry, vpsscript can not restart php-fpm service !"
	/etc/vpsscript/menu/tienich/vpsscript-restart-service
		fi
fi
fi
