#!/bin/bash 

. /home/vpsscript.conf
clear
echo "========================================================================="
echo "Your VPS  Virtualization:"
echo "-------------------------------------------------------------------------"
virt-what
/etc/vpsscript/menu/vpsscript-tien-ich
