#!/bin/sh

# Nhập email để nhận thông báo
echo "========================================================================="
echo -n "Email nhận thông báo update [ENTER]: " 
read emailmanage

# Cập nhật hệ thống và cài đặt unattended-upgrades
apt update
apt install -y unattended-upgrades mailutils

# Kiểm tra xem unattended-upgrades đã được cài đặt chưa
if ! dpkg -l | grep -q unattended-upgrades; then
    echo "========================================================================="
    echo "ERROR! unattended-upgrades không thể cài đặt..."
    exit 1
fi

# Tạo bản sao lưu tệp cấu hình
curTime=$(date +%d%H%M)
echo "curTime: $curTime"
cp /etc/apt/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/50unattended-upgrades-$curTime.bak

# Cấu hình unattended-upgrades
echo "Configuring unattended-upgrades..."
cat > "/etc/apt/apt.conf.d/50unattended-upgrades" <<END
Unattended-Upgrade::Allowed-Origins {
    "Ubuntu focal-security";
    "Ubuntu focal-updates";
};

Unattended-Upgrade::Package-Blacklist {
    // Đặt danh sách các gói không muốn tự động cập nhật, ví dụ:
    "php*";
};

Unattended-Upgrade::Mail "$emailmanage";
Unattended-Upgrade::MailOnlyOnError "true";

Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";
END

# Bật dịch vụ unattended-upgrades
echo "Enabling unattended-upgrades..."
dpkg-reconfigure -f noninteractive unattended-upgrades

# Khởi động dịch vụ
systemctl restart unattended-upgrades
systemctl enable unattended-upgrades

# Xem log cập nhật gần đây
echo "========================================================================="
echo "Log cập nhật hệ thống:"
tail -50 /var/log/unattended-upgrades/unattended-upgrades.log
