#!/bin/bash

# Kiểm tra quyền root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Vui lòng chạy script này với quyền root."
  exit 1
fi

# Kiểm tra tham số mật khẩu MySQL root
if [ -z "$1" ]; then
  echo "Vui lòng truyền mật khẩu MySQL root."
  exit 1
fi

MYSQL_ROOT_PASSWORD=$1

# Kiểm tra tham số tên database
if [ -z "$2" ]; then
  echo "Vui lòng truyền tên database muốn xóa."
  exit 1
fi
DB_NAME=$2

# Kiểm tra sự tồn tại của database
DB_EXISTS=$(mysql --user=root --password="$MYSQL_ROOT_PASSWORD" -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '$DB_NAME';" 2>/dev/null | grep -v "SCHEMA_NAME" | grep -w "$DB_NAME")

if [ -z "$DB_EXISTS" ]; then
  echo "Error: Database '$DB_NAME' không tồn tại."
  exit 1
else
  # Xóa database
  mysql --user=root --password="$MYSQL_ROOT_PASSWORD" -e "DROP DATABASE $DB_NAME;"

  # Kiểm tra kết quả của lệnh drop database
  if [ $? -eq 0 ]; then
    echo "Database '$DB_NAME' đã được xóa thành công."
  else
    echo "Error: Không thể xóa database '$DB_NAME'."
    exit 1
  fi

  # Kiểm tra lại sau khi xóa để chắc chắn
  DB_STILL_EXISTS=$(mysql --user=root --password="$MYSQL_ROOT_PASSWORD" -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '$DB_NAME';" 2>/dev/null | grep -v "SCHEMA_NAME" | grep -w "$DB_NAME")

  if [ -n "$DB_STILL_EXISTS" ]; then
    echo "Warning: Database '$DB_NAME' vẫn còn tồn tại sau khi cố gắng xóa."
    exit 1
  fi
fi
