#!/bin/bash

# Kiểm tra quyền root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Vui lòng chạy script này với quyền root."
  exit 1
fi

# Kiểm tra tham số mật khẩu MySQL root
if [ -z "$1" ]; then
  echo "Error: Vui lòng truyền mật khẩu MySQL root."
  exit 1
fi

MYSQL_ROOT_PASSWORD=$1

# Câu truy vấn để lấy tên database và người dùng, bỏ qua các system db
query="SELECT db_name, IFNULL(GROUP_CONCAT(DISTINCT user SEPARATOR ', '), '') AS users
       FROM (
         SELECT table_schema AS db_name, user FROM information_schema.SCHEMA_PRIVILEGES
         WHERE table_schema NOT IN ('mysql', 'information_schema', 'performance_schema', 'sys')
       ) AS db_users
       GROUP BY db_name;"

# Chạy truy vấn và hiển thị kết quả
mysql --user=root --password="$MYSQL_ROOT_PASSWORD" -e "$query" --skip-column-names
