#!/bin/bash

# Kiểm tra quyền root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Vui lòng chạy script này với quyền root."
  exit 1
fi

# Kiểm tra tham số mật khẩu MySQL root
if [ -z "$1" ]; then
  echo "Error: Vui lòng truyền mật khẩu MySQL root."
  exit 1
fi

MYSQL_ROOT_PASSWORD=$1

# Liệt kê danh sách các database
mysql --user=root --password="$MYSQL_ROOT_PASSWORD" -e "SHOW DATABASES;"
