#!/bin/bash
. /home/vpsscript.conf

# copy code tu file install sang
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/raymonditweb/okvip-vpsscript/master/script/vpsscript/menu/git-clone
chmod +x /root/git-clone
bash /root/git-clone


# BEGIN update OKVIP-VPSSCRIPT main
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
yes | cp -rf /opt/okvip_vpsscript/script/vpsscript/motd /etc/motd

yes | cp -rf /opt/okvip_vpsscript/script/vpsscript/calc /bin/calc && chmod +x /bin/calc
fi
yes | cp -rf /opt/okvip_vpsscript/script/vpsscript/vpsscript /bin/vpsscript && chmod +x /bin/vpsscript
# BEGIN update OKVIP-VPSSCRIPT main


rm -rf /home/vpsscript.demo/errorpage_html/*
yes | cp -rf /opt/okvip_vpsscript/script/vpsscript/errorpage_html/. /home/vpsscript.demo/errorpage_html/


# BEGIN update OKVIP-VPSSCRIPT menu
#rm -rf /etc/vpsscript/menu/*
#yes | cp -rf /opt/okvip_vpsscript/script/vpsscript/menu/. /etc/vpsscript/menu/

# Chmod 755 Menu
#/opt/okvip_vpsscript/script/vpsscript/menu/chmod-755-menu
# END update OKVIP-VPSSCRIPT menu


# confirm done update
yes | cp -rf /opt/okvip_vpsscript/version /etc/vpsscript/vpsscript.version


#rm -rf /opt/okvip_vpsscript/*
#rm -rf /opt/okvip_vpsscript
sleep 1

# enable auto update system
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
    if [ -f /etc/vpsscript/menu/auto-update-system ]; then
        clear && bash /etc/vpsscript/menu/auto-update-system
    fi
else
echo "Auto update system in CentOS 7 only"
#/etc/vpsscript/menu/vpsscript-update-upgrade-service-menu
/etc/vpsscript/menu/centos9/option/update-upgrade-service-menu
fi

#exit
