#!/bin/bash

# https://packagecloud.io/varnishcache/
# https://packagecloud.io/varnishcache/varnish63/install#bash-rpm

/etc/vpsscript/menu/varnish/install-varnish-begin
echo "6.3" > /etc/vpsscript/varnish.version
echo "6" > /etc/vpsscript/varnish.config

curl -s https://packagecloud.io/install/repositories/varnishcache/varnish63/script.rpm.sh | sudo bash

/etc/vpsscript/menu/varnish/install-varnish-end
