#!/bin/bash

# https://packagecloud.io/varnishcache/
# https://packagecloud.io/varnishcache/varnish40/install#bash-rpm

/etc/vpsscript/menu/varnish/install-varnish-begin
echo "4.1" > /etc/vpsscript/varnish.version
echo "4" > /etc/vpsscript/varnish.config

curl -s https://packagecloud.io/install/repositories/varnishcache/varnish41/script.rpm.sh | sudo bash

/etc/vpsscript/menu/varnish/install-varnish-end
